apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking-microservies
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers: "4 256k"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "256k"
    nginx.ingress.kubernetes.io/client-header-buffer-size: "64k"
    nginx.ingress.kubernetes.io/http2-max-field-size: "16k"
    nginx.ingress.kubernetes.io/http2-max-header-size: "128k"
    nginx.ingress.kubernetes.io/large-client-header-buffers: "8 64k"    
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - booking-microservices.com
    secretName: booking-tls        
  rules:                  
    - host: booking-microservices.com
      http:
        paths:
          - path: /identity
            pathType: Prefix
            backend:
              service:
                name: flight
                port:
                  number: 80
          - path: /identity/(.+)
            pathType: Prefix
            backend:
              service:
                name: identity
                port:
                  number: 80


          - path: /flight
            pathType: Prefix
            backend:
              service:
                name: flight
                port:
                  number: 80
          - path: /flight/(.+)
            pathType: Prefix
            backend:
              service:
                name: flight
                port:
                  number: 80


          - path: /passenger
            pathType: Prefix
            backend:
              service:
                name: passenger
                port:
                  number: 80                  
          - path: /passenger/(.+)
            pathType: Prefix
            backend:
              service:
                name: passenger
                port:
                  number: 80


          - path: /booking
            pathType: Prefix
            backend:
              service:
                name: booking
                port:
                  number: 80                    
          - path: /booking/(.+)
            pathType: Prefix
            backend:
              service:
                name: booking
                port:
                  number: 80                                                                