version: "3.3"
services:

    #######################################################
    #  Gateway
    #######################################################
  gateway:
    image: gateway
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/ApiGateway/Dockerfile
    container_name: booking-gateway
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db
      - rabbitmq
      # - mongo
    links:
      - db
      - rabbitmq
      # - mongo
    volumes:
        - '${USERPROFILE}\.aspnet\https:/https/'
    environment:
        - 'ASPNETCORE_URLS=https://+;http://+'
        - ASPNETCORE_HTTPS_PORT=5001
        - ASPNETCORE_Kestrel__Certificates__Default__Password=password
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
      - booking


    #######################################################
    #  Flight
    #######################################################
  flight:
    image: flight
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Flight/Dockerfile
    container_name: flight
    ports:
      - 5004:80
      - 5003:443
    depends_on:
      - db
      - rabbitmq
      # - mongo
    volumes:
        - '${USERPROFILE}\.aspnet\https:/https/'
    environment:
        - 'ASPNETCORE_URLS=https://+;http://+'
        - ASPNETCORE_HTTPS_PORT=5003
        - ASPNETCORE_Kestrel__Certificates__Default__Password=password
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
      - booking


    #######################################################
    #  Identity
    #######################################################
  identity:
    image: identity
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Identity/Dockerfile
    container_name: identity
    ports:
      - 6005:80
      - 5005:443
    depends_on:
      - db
      - rabbitmq
      # - mongo
    links:
      - db
      - rabbitmq
      # - mongo
    volumes:
        - '${USERPROFILE}\.aspnet\https:/https/'
    environment:
        - 'ASPNETCORE_URLS=https://+;http://+'
        - ASPNETCORE_HTTPS_PORT=5005
        - ASPNETCORE_Kestrel__Certificates__Default__Password=password
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
      - booking


    #######################################################
    #  Passenger
    #######################################################
  passenger:
    image: passenger
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Passenger/Dockerfile
    container_name: passenger
    ports:
      - 6012:80
      - 5012:443
    depends_on:
      - db
      - rabbitmq
      # - mongo
    links:
      - db
      - rabbitmq
      # - mongo
    volumes:
        - '${USERPROFILE}\.aspnet\https:/https/'
    environment:
        - 'ASPNETCORE_URLS=https://+;http://+'
        - ASPNETCORE_HTTPS_PORT=5012
        - ASPNETCORE_Kestrel__Certificates__Default__Password=password
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
      - booking


    #######################################################
    #  Booking
    #######################################################
  booking:
    image: booking
    build:
      args:
        Version: "1"
      context: ../../
      dockerfile: src/Services/Booking/Dockerfile
    container_name: booking
    ports:
      - 6010:80
      - 5010:443
    depends_on:
      - db
      - rabbitmq
      # - mongo
    links:
      - db
      - rabbitmq
      # - mongo
    volumes:
        - '${USERPROFILE}\.aspnet\https:/https/'
    environment:
        - 'ASPNETCORE_URLS=https://+;http://+'
        - ASPNETCORE_HTTPS_PORT=5010
        - ASPNETCORE_Kestrel__Certificates__Default__Password=password
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    networks:
      - booking


networks:
  booking:
    name: booking

volumes:
  db-data:
    external: false

